### ISSUE TITLE
How can I use this in a block?

### ISSUE THREAD

**Issue by rlb222** [bnomei/kirby3-fontselector#3]
What do I have to alter in the code to let this plugin **support blocks**?

When I put the two fields in a page blueprint and inside a block (see below), 
the second field is no longer responding to the value of the first field.

I think the lines like `this.$store.getters["content/values"]()[this.watchField]` in FontWeight.vue need to be adjusted, but I have no clue in which way (being a novice at Vue and Vuex).
Because of the possibility of multiple rows a block can have, there must be some code included to refer to the correct row a field is in, I suppose.

Hopefully you can help!
Thanks, René

```
# sandbox.yml (partly)
main:
 sections:
  fields:
   type: fields
   fields:
    myblocks:
     label: MijnBlokken
     type: blocks
     fieldsets:
      myDemo:
        wysiwyg: true
        preview: fields
        fields:
          headlinefont:
            type: fontfamily
            default: Merriweather
            required: true
                  
          headlineh1weight:
            type: fontweight
            watchField: headlinefont
            default: 700
            required: true
```
